SystemCode/MRCard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Recommender.urls')),
    # path('Recommender/', include('Recommender.urls')),
    path('admin/', admin.site.urls),
]

SystemCode/Recommender/urls.py
from django.urls import path

from . import views

app_name = 'Recommender'
urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('eligibility/', views.eligibility, name='eligibility'),
    path('preferences/', views.preferences, name='preferences'),
    path('spending_checkbox/', views.spending_checkbox, name='spending_checkbox'),
    path('spending_amount/', views.spending_amount, name='spending_amount'),
    path('recommendation/', views.recommendation, name='recommendation'),
    path('no_recommendation/', views.no_recommendation, name='no_recommendation'),
    path('test/', views.test, name='test')
    #path('spending/', views.spending, name='spending'),
    #path('bank/', views.bank, name='bank'),
    #path('end/', views.end, name='end')
]

SystemCode/Recommender/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from .models import CreditCards
from .config import *
from .rules import *

debug = True

# Functions used below
def retrieve_data_or_set_to_default(input_dict, default_dict, expecting_lists=False):
    ''' 
    Given a dictionary of data (e.g. from the HTML POST request) and a default dictionary.
    For fields that are not in the dictionary of data but in the default dictionary, assign the new fields as the default.
    '''
    output_dict = {}
    for key in default_dict.keys():
        if expecting_lists:
            try: 
                val = input_dict.getlist(key) # Check if key exists (for list)
                if len(val) == 0:
                    output_dict[key] = default_dict[key]
                else:
                    output_dict[key] = [convert_string_to_int_or_float(x) for x in val]
            except:
                output_dict[key] = default_dict[key]
        else:
            try:
                val = input_dict[key] # Check if key exists (for non-list)
                if len(val) == 0: # If it is empty
                    output_dict[key] = default_dict[key]
                else:
                    output_dict[key] = convert_string_to_int_or_float(val) 
            except:
                output_dict[key] = default_dict[key] 
    return output_dict

def convert_string_to_int_or_float(string):
    '''
    Converts the string which can contain a string, int or float, into a string, int or float
    (I'm sure there's a better way to do this.)
    '''
    try:
        output = int(string)    
        return output
    except:
        try:
            output = float(string)
            return output
        except:
            return string.lower()
    return string.lower()
    
def retrieve_subset_out_of_query_set(query_set, list_of_keys):
    '''
    Takes a QuerySet object from django in the format [{}], i.e. list of dictionaries &
    a list of keys that forms a subset of the keys of the dictionaries

    Returns a list of dictionaries of the format [{}], that is a smaller subset
    '''
    subset_of_query_set = []
    for i in range(len(query_set)):
        sub_dictionary = {}
        for key in list_of_keys:
            item = query_set[i][key]
            try:
                processed_item = [convert_string_to_int_or_float(x) for x in item.split(',')]
                if key == 'credit_card_name':
                    processed_item = [x for x in item.split(',')] # Don't lower for Credit Card Names
            except:
                if key == 'credit_card_name':
                    processed_item = [item] # Don't lower for Credit Card Names
                else:
                    processed_item = [convert_string_to_int_or_float(item)]
            sub_dictionary[key] = processed_item
        subset_of_query_set.append(sub_dictionary)
    return subset_of_query_set

def map_POST_to_session(request, expecting_lists=False):
    key_list = list(request.POST.keys())
    key_list.remove('csrfmiddlewaretoken')
    for key in key_list:
        if expecting_lists:
            request.session[key] = request.POST.getlist(key)
        else:
            request.session[key] = request.POST[key] 

def return_subset_out_of_spending_rewards_info_by_cardid(list_of_dict_of_credit_card_spending_rewards_info, list_of_card_ids):
    subset_of_spending_rewards_info = []
    for credit_card in list_of_dict_of_credit_card_spending_rewards_info:
        if str(credit_card['credit_card_id'][0]) in list_of_card_ids or credit_card['credit_card_id'][0] in list_of_card_ids:
            subset_of_spending_rewards_info.append(credit_card)
    return subset_of_spending_rewards_info

# Views Proper #
def eligibility(request):
    # This is the second html page
    return render(request, 'Recommender/eligibility.html')

def welcome(request):
    # This is the first html page
    return render(request, 'Recommender/welcome.html')

def test(request):
    # This is the test html page
    return render(request, 'Recommender/test.html')

def preferences(request):
    # This is the third html page
    map_POST_to_session(request) # Save the POST data into the session
    
    ### Process Data to determine eligibility ###
    ## Retrieve Personal eligibility info ##
    personal_info = retrieve_data_or_set_to_default(request.POST, personal_info_default_dict)
    ## Retrieve Credit Card eligibility related info ##
    all_credit_card_info = CreditCards.objects.values()
    credit_card_eligibility_info = retrieve_subset_out_of_query_set(all_credit_card_info, credit_card_eligibility_list)
    #print(credit_card_eligibility_info)
    if debug:
        print("---- Personal Info ----")
        print(personal_info)
        print("---- Credit Card Eligibility Info ----")
        print(credit_card_eligibility_info)
    ## Calculate the eligible Credit Cards here ##
    eligible_credit_card_ids = return_eligibile_credit_card_ids(personal_info, credit_card_eligibility_info) 
    if debug:
        print("---- Eligible Credit Cards ----")
        print(eligible_credit_card_ids)
    request.session['eligible_credit_card_ids'] = eligible_credit_card_ids['eligible_credit_card_ids']
    if len(eligible_credit_card_ids['eligible_credit_card_ids']) == 0:
        return render(request, 'Recommender/no_recommendation.html')
    else:
        return render(request, 'Recommender/preferences.html')


def spending_checkbox(request):
    # This is the fourth html page
    map_POST_to_session(request, True) # Save the POST data into the session
    
    ### Process Data to determine preference ###
    ## Retrieve Preference info ##
    print(request.POST)
    preference_info = retrieve_data_or_set_to_default(request.POST, preference_info_default_dict, True)
    ## Retrieve Credit Card preference related info ##
    all_credit_card_info = CreditCards.objects.values()
    credit_card_preference_info = retrieve_subset_out_of_query_set(all_credit_card_info, credit_card_preference_list)
    if debug:
        print("---- Preference Info ----")
        print(preference_info)
        print("---- Credit Card Preference Info ----")
        print(credit_card_preference_info)
    ## Calculate the preferred Credit Cards here ##
    preferred_credit_card_ids = return_preferred_credit_card_ids(preference_info, credit_card_preference_info)
    if debug:
        print("---- Preferred Credit Cards ----")
        print(preferred_credit_card_ids)
    request.session['preferred_credit_card_ids'] = preferred_credit_card_ids['preferred_credit_card_ids']
    return render(request, 'Recommender/spending_checkbox.html')


def spending_amount(request):
    # This is the fifth html page
    map_POST_to_session(request) # Save the POST data into the session
    print(request.POST)
    print("Session")
    print(request.session)
    ## Retrieve Spending Checkbox info ##
    spending_checkbox_info = retrieve_data_or_set_to_default(request.POST, spending_checkbox_default_dict)
    if debug:
        print("---- Spending Checkbox Info ----")
        print(spending_checkbox_info)
    ## Assign what data to show in the spending_amount.html ##
    eligible_spending = return_eligible_spendings_for_breakdown(spending_checkbox_info)
    if debug:
        print("---- Spending Breakdown Info ----")
        print(eligible_spending)
    #eligible_spending = {'eligible_spending':['bill','dining','groceries','transport']} # Get this from LD/YZ
    context = {
    'eligible_spending': eligible_spending['eligible_spending']
    }
    return render(request, 'Recommender/spending_amount.html', context)


def recommendation(request):
    # This is the last html page
    map_POST_to_session(request) # Save the POST data into the session
    
    ## Retrieve Preference info  ##
    rewards_type_preference_info = {'preferred_rewards_type': request.session['preferred_rewards_type']}
    ## Retrieve Eligible Credit Cards ##
    eligible_credit_card_ids = request.session['eligible_credit_card_ids']
    ## Retrieve Preferred Credit Cards ##
    preferred_credit_card_ids = request.session['preferred_credit_card_ids']
    ## Retrieve Spending Amounts info ##
    spending_amounts_info = retrieve_data_or_set_to_default(request.POST, spending_amounts_default_dict)
    ## Retrieve Credit Card cashback/miles/points info ##
    all_credit_card_info = CreditCards.objects.values()
    credit_card_spending_rewards_info = retrieve_subset_out_of_query_set(all_credit_card_info, credit_card_spending_rewards_list)
    ## Only provide to the Rules the cards that are Eligible and Eligible & Preferred ##
    eligible_and_preferred_credit_card_ids = [x for x in eligible_credit_card_ids if x in preferred_credit_card_ids]
    ideal_credit_card_spending_rewards_info = return_subset_out_of_spending_rewards_info_by_cardid(credit_card_spending_rewards_info, eligible_credit_card_ids)
    preferred_credit_card_spending_rewards_info = return_subset_out_of_spending_rewards_info_by_cardid(credit_card_spending_rewards_info, eligible_and_preferred_credit_card_ids)
    if debug:
        print("---- Prefered Rewards Type ----")
        print(rewards_type_preference_info)
        print("---- Eligible Credit Card IDs ----")
        print(eligible_credit_card_ids)
        print("---- Preferred Credit Card IDs ----")
        print(preferred_credit_card_ids)
        print("---- Spending Amounts Info ----")
        print(spending_amounts_info)
        print("---- Eligible and Preferred Credit Card IDs ----")
        print(eligible_and_preferred_credit_card_ids)
        print("---- Ideal Credit Card Rewards Info ----")
        print(ideal_credit_card_spending_rewards_info)
        print("---- Preferred Credit Cards Rewards Info ----")
        print(preferred_credit_card_spending_rewards_info)
    ## Calculate the Ideal & Preferred Credit Card ##

SystemCode/Recommender/templates/Recommender/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title Page-->
    <title>{% block title %}MRCard{% endblock %}</title>

    <!-- Icons font CSS-->
    <link href="{% static 'Recommender/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet"
          media="all">
    <link href="{% static 'Recommender/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet"
          media="all">
    <!-- Font special for pages-->
    <link href=https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i"
          rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'Recommender/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'Recommender/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'Recommender/vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'Recommender/css/main.css' %}" rel="stylesheet" media="all">
    {% block css %}{% endblock %}

    <!-- My CSS -->
    <link href="{% static 'Recommender/mycss/mycss.css' %}" rel="stylesheet" media="all">

</head>

<body>
<div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
    <div class="wrapper wrapper--w790">
        <div class="card card-5">
            <div class="card-heading">
                <h2 class="title">{% block formtitle %}MRCard{% endblock %}</h2>
            </div>
            <div class="card-body">
                {% block form %}
                    <form method="POST">
                        <div class="form-row m-b-55">
                            <div class="name">Name</div>
                            <div class="value">
                                <div class="row row-space">
                                    <div class="col-2">
                                        <div class="input-group-desc">
                                            <input class="input--style-5" type="text" name="first_name">
                                            <label class="label--desc">first name</label>
                                        </div>
                                    </div>
                                    <div class="col-2">
                                        <div class="input-group-desc">
                                            <input class="input--style-5" type="text" name="last_name">
                                            <label class="label--desc">last name</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Company</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" name="company">
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Email</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="email" name="email">
                                </div>
                            </div>
                        </div>
                        <div class="form-row m-b-55">
                            <div class="name">Phone</div>
                            <div class="value">
                                <div class="row row-refine">
                                    <div class="col-3">
                                        <div class="input-group-desc">
                                            <input class="input--style-5" type="text" name="area_code">
                                            <label class="label--desc">Area Code</label>
                                        </div>
                                    </div>
                                    <div class="col-9">
                                        <div class="input-group-desc">
                                            <input class="input--style-5" type="text" name="phone">
                                            <label class="label--desc">Phone Number</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Subject</div>
                            <div class="value">
                                <div class="input-group">
                                    <div class="rs-select2 js-select-simple select--no-search">
                                        <select name="subject">
                                            <option disabled="disabled" selected="selected">Choose option</option>
                                            <option>Subject 1</option>
                                            <option>Subject 2</option>
                                            <option>Subject 3</option>
                                        </select>
                                        <div class="select-dropdown"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row p-t-20">
                            <label class="label label--block">Are you an existing customer?</label>
                            <div class="p-t-15">
                                <label class="radio-container m-r-55">Yes
                                    <input type="radio" checked="checked" name="exist">
                                    <span class="checkmark"></span>
                                </label>
                                <label class="radio-container">No
                                    <input type="radio" name="exist">
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                        </div>
                        <div>
                            <button class="btn btn--radius-2 btn--red" type="submit">Register</button>
                        </div>
                    </form>
                {% endblock %}

            </div>
        </div>
    </div>
</div>

<!-- Jquery JS-->
<script src="{% static 'Recommender/vendor/jquery/jquery.min.js' %}"></script>
<!-- Vendor JS-->
<script src="{% static 'Recommender/vendor/select2/select2.min.js' %}"></script>
<script src="{% static 'Recommender/vendor/datepicker/moment.min.js' %}"></script>
<script src="{% static 'Recommender/vendor/datepicker/daterangepicker.js' %}"></script>

<!-- Main JS-->
<script src="{% static 'Recommender/js/global.js' %}"></script>

</body>

</html>
<!-- end document-->

SystemCode/Recommender/templates/Recommender/eligibility.html
{% extends "Recommender/base.html" %}

{% block form %}
    <form action="{% url 'Recommender:preferences' %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="name">Annual Income</div>
            <div class="value">
                <div class="input-group">
                    <input class="input--style-5" type="number" name="annual_income" placeholder="Your Annual Income"
                           required>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="name">Age</div>
            <div class="value">
                <div class="input-group">
                    <input class="input--style-5" type="number" name="age" placeholder="Your Age" required/>
                </div>
            </div>
        </div>
        <div class="form-row">
            <label class="label label--block">Gender</label>
            <div class="p-t-15">
                <label class="radio-container m-r-55">Female
                    <input type="radio" checked="checked" name="gender" value="female"/>
                    <span class="checkmark"></span>
                </label>
                <label class="radio-container">Male
                    <input type="radio" name="gender" value="male"/>
                    <span class="checkmark"></span>
                </label>
            </div>
        </div>
        <div class="form-row">
            <div class="name">Subject</div>
            <div class="value">
                <div class="input-group">
                    <div class="rs-select2 js-select-simple select--no-search">
                        <select name="citizenship" required>
                            <option disabled="disabled" selected="selected">Choose option</option>
                            <option value="singaporean">Singaporean</option>
                            <option value="pr">Permanent Resident</option>
                            <option value="foreigner">Foreigner</option>
                        </select>
                        <div class="select-dropdown"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-right">
            <button class="btn btn--radius-2 btn--red" type="submit">Next</button>
        </div>
    </form>
{% endblock %}

SystemCode/Recommender/templates/Recommender/no_recommendation.html
{% extends "Recommender/base.html" %}

{% block form %}
    <div class="pricing-header px-3 py-3 pt-md-0 pb-md-4 mt-2 mx-auto text-center">
        <h1 class="display-4 mb-5">Oops...</h1>
        <p class="lead">Sorry you are not eligible for any Credit Cards.</p>
    </div>
{% endblock %}

SystemCode/Recommender/templates/Recommender/preferences.html
{% extends "Recommender/base.html" %}

{% block form %}
    <form action="{% url 'Recommender:spending_checkbox' %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <label class="label label--block">Preferred Bank</label>
            <div class="value">
                <div class="my-input-group custom-control custom-checkbox">
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="dbs" type="checkbox" name="preferred_bank" value="dbs">
                        <label class="custom-control-label" for="dbs">DBS</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="ocbc" type="checkbox" name="preferred_bank"
                               value="ocbc">
                        <label class="custom-control-label" for="ocbc">OCBC</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="hsbc" type="checkbox" name="preferred_bank"
                               value="hsbc">
                        <label class="custom-control-label" for="hsbc">HSBC</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="citibank" type="checkbox" name="preferred_bank"
                               value="citibank">
                        <label class="custom-control-label" for="citibank">Citibank</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="maybank" type="checkbox" name="preferred_bank"
                               value="maybank">
                        <label class="custom-control-label" for="maybank">Maybank</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="uob" type="checkbox" name="preferred_bank" value="uob">
                        <label class="custom-control-label" for="uob">UOB</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="standard chartered" type="checkbox"
                               name="preferred_bank" value="standard chartered">
                        <label class="custom-control-label" for="standard chartered">Standard Chartered</label>
                    </div>
                </div>
            </div>
        </div>

        <!-- preferred_card_type -->
        <div class="form-row">
            <label class="label label--block">Preferred Card Payment Network</label>
            <div class="value">
                <div class="my-input-group custom-control custom-checkbox">
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="visa" type="checkbox" name="preferred_card_type"
                               value="visa">
                        <label class="custom-control-label" for="visa">Visa</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="mastercard" type="checkbox" name="preferred_card_type"
                               value="mastercard">
                        <label class="custom-control-label" for="mastercard">MasterCard</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="american express" type="checkbox"
                               name="preferred_card_type" value="american express">
                        <label class="custom-control-label" for="american express">American Express</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="jcb" type="checkbox" name="preferred_card_type"
                               value="jcb">
                        <label class="custom-control-label" for="jcb">JCB</label>
                    </div>
                </div>
            </div>
        </div>

        <!-- preferred_rewards_type -->
        <div class="form-row">
            <label class="label label--block">Preferred Rewards Type</label>
            <div class="value">
                <div class="my-input-group custom-control custom-checkbox">
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="cashback" type="checkbox" name="preferred_rewards_type"
                               value="cashback">
                        <label class="custom-control-label" for="cashback">Cashback</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="miles" type="checkbox" name="preferred_rewards_type"
                               value="miles">
                        <label class="custom-control-label" for="miles">Miles</label>
                    </div>
                    <div class="custom-control custom-checkbox mr-4">
                        <input class="custom-control-input" id="rewards" type="checkbox" name="preferred_rewards_type"
                               value="points">
                        <label class="custom-control-label" for="rewards">Rewards</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="text-right">
            <button class="btn btn--radius-2 btn--red" type="submit">Next</button>
        </div>
    </form>
{% endblock %}

SystemCode/Recommender/templates/Recommender/spending_checkbox.html
{% extends "Recommender/base.html" %}

{% block form %}
    <form action="{% url 'Recommender:spending_amount' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <label class="label label--block">What do you pay by credit cards</label>
            <div class="value">
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="bill_checkbox" id="bill" value="1">
                    <label class="custom-control-label" for="bill">Bill</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="dining_checkbox" id="dining" value="1">
                    <label class="custom-control-label" for="dining">Dining</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="entertainment_checkbox" id="entertainment"
                           value="1">
                    <label class="custom-control-label" for="entertainment">Entertainment</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="foreign_checkbox" id="foreign" value="1">
                    <label class="custom-control-label" for="foreign">Foreign Spending</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="groceries_checkbox" id="groceries"
                           value="1">
                    <label class="custom-control-label" for="groceries">Groceries</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="online_shopping_checkbox" id="online"
                           value="1">
                    <label class="custom-control-label" for="online">Online</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="petrol_checkbox" id="petrol" value="1">
                    <label class="custom-control-label" for="petrol">Petrol</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="retail_shopping_checkbox" id="retail"
                           value="1">
                    <label class="custom-control-label" for="retail">Retail</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="transport_checkbox" id="transport"
                           value="1">
                    <label class="custom-control-label" for="transport">Transport</label>
                </div>
            </div>
        </div>

        <div class="text-right">
            <button class="btn btn--radius-2 btn--red" type="submit">Next</button>
        </div>
    </form>
{% endblock %}

SystemCode/Recommender/templates/Recommender/welcome.html
{% extends "Recommender/base.html" %}
{% block css %}
    <style>
        .lead {
            font-size: 1.25rem;
            font-weight: 300;
        }
    </style>
{% endblock %}

{% block form %}
    <form action="{% url 'Recommender:eligibility' %}" method="POST">
        {% csrf_token %}
        <div class="pricing-header px-3 py-3 pt-md-0 pb-md-4 mt-2 mx-auto text-center">
            <h2 class="display-4 m-b-55">MRCard</h2>
            <p class="lead m-b-55">Welcome to MRCard system, your smart choice on credit cards.</p>
        </div>
        <div class="text-center">
            <button class="btn btn--radius-2 btn--red" type="submit">Start</button>
        </div>
    </form>

{% endblock %}